#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - cd public-src
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
